{{- if .Values.dependencies.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "zipkin.dependencies.fullname" . }}
  labels:
    {{- include "zipkin.dependencies.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.dependencies.cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "zipkin.dependencies.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "zipkin.dependencies.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}-dependencies
              image: "{{ .Values.dependencies.image.repository }}:{{ .Values.dependencies.image.repository }}"
              imagePullPolicy: {{ .Values.dependencies.image.pullPolicy }}
              resources:
                {{- toYaml .Values.collector.resources | nindent 16 }}
          {{- with .Values.collector.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.collector.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.collector.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}

{{- end -}}